### PR TITLE
Fix big endianess issue for llguidance

### LINKED ISSUE #330: Grammar bitmask broken on s390x resulting to a corrupted guided decoding output
Grammar decoding is broken on s390x when using llguidance as a backend. The token bitmask produced by guidance has incorrect bit patterns on big endian platforms, causing vLLM to generate corrupted output typically infinite whitespace/tab loops instead of valid constrained JSON and when disabling infinite whitespace corrupted output is coming
```
curl http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -N \
  -X POST \
  -d '{
    "model": "ibm-granite/granite-3.3-8b-instruct",
    "messages": [
      {
        "role": "system",
        "content": "Extract fields from log lines verbatim. Do not paraphrase or use placeholders."
      },
      {
        "role": "user",
        "content": "Parse: ERROR kubelet failed to start container"
      }
    ],
    "stream": true,
    "response_format": {
      "type": "json_schema",
      "json_schema": {
        "name": "log",
        "schema": {
          "type": "object",
          "properties": {
            "level":     { "type": "string", "enum": ["INFO", "WARNING", "ERROR"] },
            "component": { "type": "string" },
            "message":   { "type": "string" }
          },
          "required": ["level", "component", "message"]
        }
      }
    }
  }'
data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}],"prompt_token_ids":null}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":"{"},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":"\n "},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":" \""},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":"level"},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":"\":"},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":" "},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":"\t"},"logprobs":null,"finish_reason":null,"token_ids":null}]}

data: {"id":"chatcmpl-9bfd1eb74b911260","object":"chat.completion.chunk","created":1775236945,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"delta":{"content":"\n                                                     "},"logprobs":null,"finish_reason":null,"token_ids":null}]}
```
and after disabling flexible whitespace
```
curl http://localhost:8000/v1/chat/completions   -H "Content-Type: application/json"   -X POST   -d '{
    "model": "ibm-granite/granite-3.3-8b-instruct",
    "messages": [
      {
        "role": "system",
        "content": "Extract fields from log lines verbatim. Do not paraphrase or use placeholders."
      },
      {"role": "user", "content": "Parse: ERROR kubelet failed to start container"}
    ],
    "response_format": {
      "type": "json_schema",
      "json_schema": {
        "name": "log",
        "schema": {
          "type": "object",
          "properties": {
            "level":     { "type": "string", "enum": ["INFO", "WARNING", "ERROR"] },
            "component": { "type": "string" },
            "message":   { "type": "string" }
          },
          "required": ["level", "component", "message"]
        }
      }
    }
  }' 
{"id":"chatcmpl-a7116a599fdd4d17","object":"chat.completion","created":1775239513,"model":"ibm-granite/granite-3.3-8b-instruct","choices":[{"index":0,"message":{"role":"assistant","content":"{\"level\":\u0000ERROR\",\"component\":\u0000\",\"message\":\u0000\",\u0000\":\u0000\"}","refusal":null,"annotations":null,"audio":null,"function_call":null,"tool_calls":[],"reasoning":null},"logprobs":null,"finish_reason":"stop","stop_reason":null,"token_ids":null}],"service_tier":null,"system_fingerprint":null,"usage":{"prompt_tokens":38,"total_tokens":61,"completion_tokens":23,"prompt_tokens_details":null},"prompt_logprobs":null,"prompt_token_ids":null,"kv_transfer_params":null} 
```
On creating a test script for s390x to test guidance functionality seeing the following failures
1. Regex/lexer crashes on big-endian (derivre)
All grammars using regex patterns fail immediately with a lexer error:
```
[FAIL] matcher created without error -- 1(9): lexer error
   1 | start: /[0-9]+/
               ^
```
2. Bitmask bit layout is byte-swapped (SimpleVob / TokTrie)

Even for grammars that don't use regex (JSON schema, Lark literals), the bitmask produced by `fill_next_token_bitmask / unsafe_compute_mask_ptr` has incorrect bit patterns on big endian

3. compute_bitmask() byte representation is platform dependent

compute_bitmask() uses `bytemuck::cast_slice::<u32, u8>` to return the bitmask as bytes. On big endian, the byte order within each 4-byte word is reversed compared to little endian

The script used
```
#!/usr/bin/env python3
import argparse
import platform
import struct
import sys

import numpy as np

import llguidance
from llguidance import LLTokenizer, LLMatcher, LLExecutor
from llguidance.numpy import (
    allocate_token_bitmask,
    fill_next_token_bitmask,
    fill_next_token_bitmask_par,
    apply_token_bitmask_inplace,
    get_bitmask_shape,
)

PASS_COUNT = 0
FAIL_COUNT = 0


def report(name: str, ok: bool, detail: str = "") -> None:
    global PASS_COUNT, FAIL_COUNT
    if ok:
        PASS_COUNT += 1
    else:
        FAIL_COUNT += 1
    status = "PASS" if ok else "FAIL"
    msg = f"  [{status}] {name}"
    if detail:
        msg += f" -- {detail}"
    print(msg)
    if not ok:
        print(f"         ^^^ FAILURE in: {name}", file=sys.stderr)


def mask_has(mask_row: np.ndarray, token_id: int) -> bool:
    """Check if *token_id* is allowed in a bitmask row (int32 array)."""
    word_idx = token_id // 32
    bit_idx = token_id % 32
    return bool(mask_row[word_idx] & (np.int32(1) << bit_idx))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verbose", action="store_true",
                        help="Enable verbose matcher output")
    args = parser.parse_args()

    log_level = 2 if args.verbose else 1
    arch = platform.machine()
    is_big_endian = sys.byteorder == "big"

    print("=== Grammar Bitmask Test for s390x ===")
    print(f"Architecture: {arch}")
    print(f"Python:       {sys.version}")
    print()

    print("Platform info:")
    print(f"  sys.byteorder = {sys.byteorder}")
    endian_label = "big-endian" if struct.pack("@I", 1)[0] == 0 else "little-endian"
    print(f"  struct native  = {endian_label}")
    print(f"  numpy dtype    = {np.dtype(np.int32).byteorder}")
    print(f"  architecture   = {arch}")
    if is_big_endian:
        print("  Detected BIG-ENDIAN platform (s390x)")
    else:
        print("  Detected little-endian platform (emulating s390x test logic)")
    print()

    tok = LLTokenizer("byte")
    vocab_size = tok.vocab_size
    print(f"Tokenizer: byte-level, vocab_size={vocab_size}, eos={tok.eos_token}")
    print()

    print("Test 1: Bitmask allocation and shape")
    for batch in [1, 4]:
        shape = get_bitmask_shape(batch, vocab_size)
        expected_cols = (vocab_size + 31) // 32
        report(f"shape batch={batch}", shape == (batch, expected_cols),
               f"got {shape}, expected ({batch}, {expected_cols})")

    mask = allocate_token_bitmask(1, vocab_size)
    report("dtype is int32", mask.dtype == np.int32)
    report("initialized to all-ones (-1)", np.all(mask == -1),
           "all bits should be set (all tokens allowed)")
    print()

    print("Test 2: Regex grammar bitmask (/[0-9]+/)")
    grm = LLMatcher.grammar_from_regex(r"[0-9]+")
    m = LLMatcher(tok, grm, log_level=log_level)
    report("matcher created without error", not m.is_error(), m.get_error())

    mask = allocate_token_bitmask(1, vocab_size)
    fill_next_token_bitmask(m, mask)

    digits = [tok.tokenize_str(str(d))[0] for d in range(10)]
    for d in range(10):
        tid = digits[d]
        report(f"digit {d} (token {tid}) allowed", mask_has(mask[0], tid))

    alpha_tokens = [tok.tokenize_str(c)[0] for c in "abcXYZ"]
    for c, tid in zip("abcXYZ", alpha_tokens):
        report(f'alpha "{c}" (token {tid}) disallowed', not mask_has(mask[0], tid))
    print()

    print("Test 3: JSON schema grammar")
    schema = {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"},
        },
        "required": ["name", "age"],
    }
    grm = LLMatcher.grammar_from_json_schema(schema)
    m = LLMatcher(tok, grm, log_level=log_level)
    report("JSON schema matcher created", not m.is_error(), m.get_error())

    mask = allocate_token_bitmask(1, vocab_size)
    fill_next_token_bitmask(m, mask)

    open_brace = tok.tokenize_str("{")[0]
    report('"{" allowed at start', mask_has(mask[0], open_brace))
    close_paren = tok.tokenize_str(")")[0]
    report('")" disallowed at start', not mask_has(mask[0], close_paren))
    print()

    print("Test 4: Lark grammar full sequence validation")
    grm = LLMatcher.grammar_from_lark('start: /[a-zA-Z]+/ " " /[0-9]+/')
    m = LLMatcher(tok, grm, log_level=log_level)
    report("Lark matcher created", not m.is_error(), m.get_error())

    test_str = "hello 42"
    tokens = tok.tokenize_str(test_str)
    all_ok = True
    for i, t in enumerate(tokens):
        mask = allocate_token_bitmask(1, vocab_size)
        fill_next_token_bitmask(m, mask)
        if not mask_has(mask[0], t):
            report(f"token {i} ({tok.dbg_tokens([t])}) in mask", False)
            all_ok = False
            break
        m.consume_token(t)
        if m.is_error():
            report(f"consume token {i} ok", False, m.get_error())
            all_ok = False
            break

    if all_ok:
        report(f'all {len(tokens)} tokens accepted for "{test_str}"', True)
        report("matcher is accepting", m.is_accepting())
    print()

    print("Test 5: apply_token_bitmask_inplace (numpy) endianness")
    np.random.seed(42)
    test_vocab = 256
    logits = np.random.randn(1, test_vocab).astype(np.float32)
    logits_orig = logits.copy()

    bitmask = np.zeros(get_bitmask_shape(1, test_vocab), dtype=np.int32)
    allowed_ids = [0, 1, 5, 31, 32, 33, 63, 64, 100, 127, 200, 255]
    for tid in allowed_ids:
        word = tid // 32
        bit = tid % 32
        bitmask[0, word] |= np.int32(1) << bit

    apply_token_bitmask_inplace(logits, bitmask)

    correct = True
    for tid in range(test_vocab):
        if tid in allowed_ids:
            if logits[0, tid] != logits_orig[0, tid]:
                report(f"allowed token {tid} preserved", False,
                       f"got {logits[0, tid]}, expected {logits_orig[0, tid]}")
                correct = False
                break
        else:
            if not np.isinf(logits[0, tid]) or logits[0, tid] > 0:
                report(f"disallowed token {tid} set to -inf", False,
                       f"got {logits[0, tid]}")
                correct = False
                break

    if correct:
        report("allowed tokens preserved, disallowed set to -inf", True)
    print()

    print("Test 6: Bitmask bit layout consistency")
    grm = LLMatcher.grammar_from_regex(r"[a-z]")
    m = LLMatcher(tok, grm, log_level=log_level)

    bitmask_bytes = m.compute_bitmask()
    logit_bias = m.compute_logit_bias()

    mismatch = False
    for tid in range(vocab_size):
        byte_idx = tid // 8
        bit_in_byte = tid % 8
        bitmask_set = bool(bitmask_bytes[byte_idx] & (1 << bit_in_byte))
        bias_set = logit_bias[tid] == 200
        if bitmask_set != bias_set:
            report(f"token {tid} bitmask vs logit_bias agree", False,
                   f"bitmask={bitmask_set}, bias={bias_set}")
            mismatch = True
            break

    if not mismatch:
        report("compute_bitmask and compute_logit_bias agree for all tokens", True)
    print()

    print("Test 7: Parallel bitmask computation (LLExecutor)")
    executor = LLExecutor()
    g_alpha = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[a-zA-Z ]+"), log_level=log_level)
    g_digit = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[0-9 ]+"), log_level=log_level)
    g_hex   = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[0-9a-fA-F]+"), log_level=log_level)

    batch_mask = allocate_token_bitmask(3, vocab_size)
    fill_next_token_bitmask_par(
        executor, [(g_alpha, 0), (g_digit, 1), (g_hex, 2)], batch_mask
    )

    t_a = tok.tokenize_str("a")[0]
    t_1 = tok.tokenize_str("1")[0]
    t_Z = tok.tokenize_str("Z")[0]

    report('alpha matcher: "a" allowed',   mask_has(batch_mask[0], t_a))
    report('alpha matcher: "1" disallowed', not mask_has(batch_mask[0], t_1))
    report('digit matcher: "1" allowed',   mask_has(batch_mask[1], t_1))
    report('digit matcher: "a" disallowed', not mask_has(batch_mask[1], t_a))
    report('hex matcher: "a" allowed',     mask_has(batch_mask[2], t_a))
    report('hex matcher: "1" allowed',     mask_has(batch_mask[2], t_1))
    report('hex matcher: "Z" disallowed',  not mask_has(batch_mask[2], t_Z))
    print()

    print("Test 8: Simulated vLLM guided-decoding loop")
    schema = {
        "type": "object",
        "properties": {
            "city": {"type": "string", "minLength": 1},
            "temp": {"type": "number"},
        },
        "required": ["city", "temp"],
    }
    grm = LLMatcher.grammar_from_json_schema(schema)
    m = LLMatcher(tok, grm, log_level=log_level)
    report("vLLM-style matcher created", not m.is_error(), m.get_error())

    target = '{"city":"NYC","temp":72}'
    tokens = tok.tokenize_str(target)
    print(f"  Target: {target}")
    print(f"  Tokens: {tok.dbg_tokens(tokens)} ({len(tokens)} tokens)")

    steps = 0
    decode_ok = True
    for i, t in enumerate(tokens):
        mask = allocate_token_bitmask(1, vocab_size)
        fill_next_token_bitmask(m, mask)

        logits = np.zeros((1, vocab_size), dtype=np.float32)
        apply_token_bitmask_inplace(logits, mask[0:1])

        if np.isinf(logits[0, t]) and logits[0, t] < 0:
            report(f"step {i}: token allowed", False,
                   f"{tok.dbg_tokens([t])} was masked out")
            decode_ok = False
            break

        ok = m.consume_token(t)
        if not ok or m.is_error():
            report(f"step {i}: consume_token ok", False, m.get_error())
            decode_ok = False
            break
        steps += 1

    if decode_ok:
        report(f"all {steps} decode steps succeeded", True)
        report("matcher is accepting after full sequence", m.is_accepting())
    print()

    print("Test 9: Endianness-sensitive bit extraction")
    grm = LLMatcher.grammar_from_regex(r"[\x00-\x7f]")
    m = LLMatcher(tok, grm, log_level=log_level)
    if m.is_error():
        report("ASCII-range matcher created", False, m.get_error())
    else:
        raw_bitmask = m.compute_bitmask()

        mask_arr = allocate_token_bitmask(1, vocab_size)
        m2 = LLMatcher(tok, grm, log_level=log_level)
        fill_next_token_bitmask(m2, mask_arr)

        agree = True
        for tid in range(vocab_size):
            byte_idx = tid // 8
            bit_in_byte = tid % 8
            from_raw = bool(raw_bitmask[byte_idx] & (1 << bit_in_byte))

            word_idx = tid // 32
            bit_in_word = tid % 32
            from_fill = bool(mask_arr[0, word_idx] & (np.int32(1) << bit_in_word))

            if from_raw != from_fill:
                report(f"token {tid}: raw vs fill agree", False,
                       f"raw={from_raw}, fill={from_fill}")
                agree = False
                break

        if agree:
            report("compute_bitmask and fill_next_token_bitmask agree", True)
    print()

    print("Test 10: Word-boundary token IDs (bits near int32 edges)")
    grm = LLMatcher.grammar_from_lark("start: <[*]>+")
    m = LLMatcher(tok, grm, log_level=log_level)
    mask = allocate_token_bitmask(1, vocab_size)
    fill_next_token_bitmask(m, mask)

    boundary_ids = [0, 1, 30, 31, 32, 33, 62, 63, 64, 65, 95, 96, 127, 128, 255]
    boundary_ids = [t for t in boundary_ids if t < vocab_size]
    all_boundary_ok = True
    for tid in boundary_ids:
        word = tid // 32
        bit = tid % 32
        val = mask[0, word]
        is_set = bool(val & (np.int32(1) << bit))
        if not is_set:
            report(f"boundary token {tid} (word {word}, bit {bit})", False,
                   "token should be allowed by wildcard grammar")
            all_boundary_ok = False
            break

    if all_boundary_ok:
        report("all word-boundary tokens handled correctly", True)
    print()

    print("Test 11: Parallel consume_token")
    try:
        from llguidance.numpy import consume_token_par as _consume_par
        has_consume_par = True
    except ImportError:
        has_consume_par = False

    if has_consume_par:
        g1 = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[a-z]+"), log_level=log_level)
        g2 = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[0-9]+"), log_level=log_level)
        t_a = tok.tokenize_str("a")[0]
        t_1 = tok.tokenize_str("1")[0]
        results = _consume_par(executor, [(g1, t_a), (g2, t_1)])
        report("parallel consume valid tokens",
               results == [True, True], f"got {results}")

        g3 = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[a-z]+"), log_level=log_level)
        g4 = LLMatcher(tok, LLMatcher.grammar_from_regex(r"[0-9]+"), log_level=log_level)
        results2 = _consume_par(executor, [(g3, t_1), (g4, t_a)])
        report("parallel consume invalid tokens",
               results2 == [False, False], f"got {results2}")
    else:
        print("  [SKIP] consume_token_par -- not available in installed version")
    print()

    print("Test 12: Multiple grammar types (Lark, regex, JSON schema, choice)")

    grammars = [
        ("regex /[A-Z]{3}/",
         LLMatcher.grammar_from_regex(r"[A-Z]{3}"), "NYC", "nyc"),
        ("lark start: /yes|no/",
         LLMatcher.grammar_from_lark("start: /yes|no/"), "yes", "maybe"),
        ("JSON schema enum",
         LLMatcher.grammar_from_json_schema({"enum": ["red", "green", "blue"]}),
         '"red"', '"pink"'),
    ]

    for name, grm, good_str, bad_str in grammars:
        m_good = LLMatcher(tok, grm, log_level=log_level)
        good_tokens = tok.tokenize_str(good_str)
        all_accepted = True
        for t in good_tokens:
            mask = allocate_token_bitmask(1, vocab_size)
            fill_next_token_bitmask(m_good, mask)
            if not mask_has(mask[0], t):
                all_accepted = False
                break
            m_good.consume_token(t)
        report(f'{name}: "{good_str}" accepted',
               all_accepted and not m_good.is_error())

        m_bad = LLMatcher(tok, grm, log_level=log_level)
        bad_tokens = tok.tokenize_str(bad_str)
        some_rejected = False
        for t in bad_tokens:
            mask = allocate_token_bitmask(1, vocab_size)
            fill_next_token_bitmask(m_bad, mask)
            if not mask_has(mask[0], t):
                some_rejected = True
                break
            m_bad.consume_token(t)
        report(f'{name}: "{bad_str}" rejected', some_rejected)
    print()

    total = PASS_COUNT + FAIL_COUNT
    print("=" * 50)
    print(f"Results: {PASS_COUNT}/{total} passed, {FAIL_COUNT}/{total} failed")
    if is_big_endian:
        print("Platform: s390x (big-endian) - NATIVE")
    else:
        print(f"Platform: {arch} (little-endian) - logic validated")
    print("=" * 50)

    if FAIL_COUNT > 0:
        sys.exit(1)
    print("All grammar bitmask tests passed!")


if __name__ == "__main__":
    main()
```
The result
```
[root@b314lp81 ~]# python3.12 test2.py 
=== Grammar Bitmask Test for s390x ===
Architecture: s390x
Python:       3.12.9 (main, Aug 14 2025, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-5)]

Platform info:
  sys.byteorder = big
  struct native  = big-endian
  numpy dtype    = =
  architecture   = s390x
  Detected BIG-ENDIAN platform (s390x)

Tokenizer: byte-level, vocab_size=262, eos=261

Test 1: Bitmask allocation and shape
  [PASS] shape batch=1 -- got (1, 9), expected (1, 9)
  [PASS] shape batch=4 -- got (4, 9), expected (4, 9)
  [PASS] dtype is int32
  [PASS] initialized to all-ones (-1) -- all bits should be set (all tokens allowed)

Test 2: Regex grammar bitmask (/[0-9]+/)
  [FAIL] matcher created without error -- 1(9): lexer error
   1 | start: /[0-9]+/
               ^

         ^^^ FAILURE in: matcher created without error
  [FAIL] digit 0 (token 48) allowed
         ^^^ FAILURE in: digit 0 (token 48) allowed
  [FAIL] digit 1 (token 49) allowed
         ^^^ FAILURE in: digit 1 (token 49) allowed
  [FAIL] digit 2 (token 50) allowed
         ^^^ FAILURE in: digit 2 (token 50) allowed
  [FAIL] digit 3 (token 51) allowed
         ^^^ FAILURE in: digit 3 (token 51) allowed
  [FAIL] digit 4 (token 52) allowed
         ^^^ FAILURE in: digit 4 (token 52) allowed
  [FAIL] digit 5 (token 53) allowed
         ^^^ FAILURE in: digit 5 (token 53) allowed
  [FAIL] digit 6 (token 54) allowed
         ^^^ FAILURE in: digit 6 (token 54) allowed
  [FAIL] digit 7 (token 55) allowed
         ^^^ FAILURE in: digit 7 (token 55) allowed
  [FAIL] digit 8 (token 56) allowed
         ^^^ FAILURE in: digit 8 (token 56) allowed
  [FAIL] digit 9 (token 57) allowed
         ^^^ FAILURE in: digit 9 (token 57) allowed
  [PASS] alpha "a" (token 97) disallowed
  [PASS] alpha "b" (token 98) disallowed
  [PASS] alpha "c" (token 99) disallowed
  [PASS] alpha "X" (token 88) disallowed
  [PASS] alpha "Y" (token 89) disallowed
  [PASS] alpha "Z" (token 90) disallowed

Test 3: JSON schema grammar
  [PASS] JSON schema matcher created
  [PASS] "{" allowed at start
  [PASS] ")" disallowed at start

Test 4: Lark grammar full sequence validation
  [FAIL] Lark matcher created -- 1(9): lexer error
   1 | start: /[a-zA-Z]+/ " " /[0-9]+/
               ^

         ^^^ FAILURE in: Lark matcher created
  [FAIL] token 0 (⟦h⟧) in mask
         ^^^ FAILURE in: token 0 (⟦h⟧) in mask

Test 5: apply_token_bitmask_inplace (numpy) endianness
  [PASS] allowed tokens preserved, disallowed set to -inf

Test 6: Bitmask bit layout consistency
  [FAIL] token 261 bitmask vs logit_bias agree -- bitmask=False, bias=True
         ^^^ FAILURE in: token 261 bitmask vs logit_bias agree

Test 7: Parallel bitmask computation (LLExecutor)
  [FAIL] alpha matcher: "a" allowed
         ^^^ FAILURE in: alpha matcher: "a" allowed
  [PASS] alpha matcher: "1" disallowed
  [FAIL] digit matcher: "1" allowed
         ^^^ FAILURE in: digit matcher: "1" allowed
  [PASS] digit matcher: "a" disallowed
  [FAIL] hex matcher: "a" allowed
         ^^^ FAILURE in: hex matcher: "a" allowed
  [FAIL] hex matcher: "1" allowed
         ^^^ FAILURE in: hex matcher: "1" allowed
  [PASS] hex matcher: "Z" disallowed

Test 8: Simulated vLLM guided-decoding loop
  [PASS] vLLM-style matcher created
  Target: {"city":"NYC","temp":72}
  Tokens: ⟦{‧"‧c‧i‧t‧y‧"‧:‧"‧N‧Y‧C‧"‧,‧"‧t‧e‧m‧p‧"‧:‧7‧2‧}⟧ (24 tokens)
  [FAIL] step 8: token allowed -- ⟦"⟧ was masked out
         ^^^ FAILURE in: step 8: token allowed

Test 9: Endianness-sensitive bit extraction
  [FAIL] ASCII-range matcher created -- 1(9): lexer error
   1 | start: /[\x00-\x7f]/
               ^

         ^^^ FAILURE in: ASCII-range matcher created

Test 10: Word-boundary token IDs (bits near int32 edges)
  [FAIL] boundary token 0 (word 0, bit 0) -- token should be allowed by wildcard grammar
         ^^^ FAILURE in: boundary token 0 (word 0, bit 0)

Test 11: Parallel consume_token
  [FAIL] parallel consume valid tokens -- got [False, False]
         ^^^ FAILURE in: parallel consume valid tokens
  [PASS] parallel consume invalid tokens -- got [False, False]

Test 12: Multiple grammar types (Lark, regex, JSON schema, choice)
  [FAIL] regex /[A-Z]{3}/: "NYC" accepted
         ^^^ FAILURE in: regex /[A-Z]{3}/: "NYC" accepted
  [PASS] regex /[A-Z]{3}/: "nyc" rejected
  [FAIL] lark start: /yes|no/: "yes" accepted
         ^^^ FAILURE in: lark start: /yes|no/: "yes" accepted
  [PASS] lark start: /yes|no/: "maybe" rejected
  [FAIL] JSON schema enum: ""red"" accepted
         ^^^ FAILURE in: JSON schema enum: ""red"" accepted
  [PASS] JSON schema enum: ""pink"" rejected

==================================================
Results: 22/47 passed, 25/47 failed
Platform: s390x (big-endian) - NATIVE
==================================================
```
with the same script it passes on x86

### PR DESCRIPTION
**Pull request by R3hankhan123**
Fix `compute_bitmask()`, `compute_mask_into()`, and `SimpleVob::write_to()` to always produce little-endian bytes, ensuring consistent cross-platform behavior on big-endian architectures like s390x 

On s390x, three APIs that serialize the internal `u32` bitmask to `&[u8]` used `bytemuck::cast_slice`, which produces **platform-native** byte order. Consumers of these byte streams (Python code, tests) assume little-endian layout, causing bit positions to be misinterpreted on s390x.

Fixes #330

### CODE REVIEW

**Comment by hudson-ai** [comment]
Awesome, thanks!

I think that all three changed sites can be re-written to use a shared helper, i.e. something with signature like:
`write_u32s_as_le_bytes(words: &[u32], dst: &mut [u8])`

`toktrie::bytes` would probably be a natural place to put this

**Comment by R3hankhan123** [comment]
@hudson-ai done, can you please take a look thanks

File: toktrie/src/bytes.rs [hunk 1]
```diff
@@ -13,6 +13,20 @@ pub fn clone_vec_as_bytes<T: NoUninit>(input: &[T]) -> Vec<u8> {
     bytemuck::cast_slice(input).to_vec()
 }
 
+/// Write `&[u32]` into `&mut [u8]` in little-endian byte order.
+/// This is safe to call on any platform and guarantees a consistent
+/// byte layout regardless of native endianness.
```
Comment (hudson-ai) [inline toktrie/src/bytes.rs:18]: Small nit: could you expand the docstring to say what happens when dst is shorter than the serialized bytes, and when it is longer?

**Comment by hudson-ai** [comment]
Looks good -- thanks for the quick turnaround here! Just one nit on docstrings :)

File: toktrie/src/bytes.rs (hunk 1 above)
Comment (riedgar-ms) [reply toktrie/src/bytes.rs:18]: That behaviour could also be put into test cases in this file, perhaps? I appreciate that for little-endian the test cases may be rather dull.

Comment (R3hankhan123) [reply toktrie/src/bytes.rs:18]: @hudson-ai i have updated the docstring

Comment (R3hankhan123) [reply toktrie/src/bytes.rs:18]: @riedgar-ms i have added some test cases can you review it thanks

**Review by riedgar-ms — APPROVED** [review]
No objections from me
